# Generated by Django 6.0.6 on 2026-06-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='e.g. UPCOMING SOON', max_length=200, verbose_name='Main Title')),
                ('subtitle', models.CharField(blank=True, help_text='e.g. Your One-Stop Online Shopping Destination', max_length=300, verbose_name='Subtitle')),
                ('badge_text', models.CharField(blank=True, help_text='e.g. UP TO 50% OFF', max_length=100, verbose_name='Badge Text')),
                ('button_text', models.CharField(default='Shop Now', max_length=80, verbose_name='Button Text')),
                ('button_link', models.CharField(default='/home/', max_length=200, verbose_name='Button URL')),
                ('image', models.ImageField(blank=True, help_text='Right side product collage image', null=True, upload_to='hero_banners/', verbose_name='Banner Image')),
                ('bg_color', models.CharField(default='#f0f0f0', help_text='CSS color e.g. #f0f0f0 or white', max_length=20, verbose_name='Background Color')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HomeBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Brand Name')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='home_brands/', verbose_name='Brand Logo')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Brand URL / Filter Link')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Top Brand',
                'verbose_name_plural': 'Top Brands',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeCategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Category Display Name')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home_categories/', verbose_name='Category Image / Icon')),
                ('link_url', models.CharField(blank=True, help_text='e.g. /home/?category=mobile-phones', max_length=255, verbose_name='Link URL')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Homepage Category',
                'verbose_name_plural': 'Homepage Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='HomeFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(choices=[('bi-truck', 'Truck (Delivery)'), ('bi-shield-lock', 'Shield (Security)'), ('bi-arrow-repeat', 'Arrows (Returns)'), ('bi-headset', 'Headset (Support)'), ('bi-gift', 'Gift'), ('bi-star', 'Star'), ('bi-credit-card', 'Credit Card'), ('bi-box-seam', 'Box'), ('bi-tag', 'Tag (Discount)')], default='bi-truck', max_length=60, verbose_name='Bootstrap Icon Class')),
                ('title', models.CharField(help_text='e.g. FREE DELIVERY', max_length=100, verbose_name='Feature Title')),
                ('description', models.CharField(blank=True, help_text='e.g. On All Orders', max_length=200, verbose_name='Short Description')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Homepage Feature',
                'verbose_name_plural': 'Homepage Features',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PromoBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(help_text='e.g. THIS WEBSITE IS', max_length=200, verbose_name='Main Title')),
                ('highlight_text', models.CharField(help_text='e.g. UPCOMING SOON', max_length=200, verbose_name='Highlighted Text')),
                ('sub_text', models.CharField(blank=True, help_text='e.g. STAY TUNED!', max_length=200, verbose_name='Sub Text')),
                ('developer_name', models.CharField(blank=True, max_length=150, verbose_name='Developer Name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Contact Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Contact Phone')),
                ('bg_color', models.CharField(default='#ffb800', help_text='CSS color e.g. #ffb800', max_length=20, verbose_name='Background Color')),
                ('side_image', models.ImageField(blank=True, help_text='Coming Soon / Product image on right side', null=True, upload_to='promo_banners/', verbose_name='Right Side Image')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Promotional Banner',
                'verbose_name_plural': 'Promotional Banners',
            },
        ),
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Legacy Banner', 'verbose_name_plural': 'Legacy Banners'},
        ),
        migrations.AlterModelOptions(
            name='slider',
            options={'verbose_name': 'Legacy Slider', 'verbose_name_plural': 'Legacy Sliders'},
        ),
    ]
