# Generated by Django 6.0.6 on 2026-06-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_homepagesettings_homepagefeature_homepagecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120, verbose_name='Banner Title')),
                ('image', models.ImageField(upload_to='banners/', verbose_name='Banner Image')),
                ('link_url', models.CharField(blank=True, max_length=255, verbose_name='Banner Link URL')),
                ('display_order', models.PositiveSmallIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Banners',
                'ordering': ['display_order', 'created_at', 'id'],
            },
        ),
    ]
