# Generated by Django 6.0.6 on 2026-06-25 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/carousel/', verbose_name='Carousel Image')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Slide Title')),
                ('redirect_url', models.URLField(blank=True, max_length=500, verbose_name='Redirect URL')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('slide_duration', models.PositiveIntegerField(default=5000, verbose_name='Slide Duration (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Homepage Carousel',
                'verbose_name_plural': 'Homepage Carousels',
                'ordering': ['display_order', 'created_at', 'id'],
            },
        ),
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
