# Generated by Django 6.0.6 on 2026-06-25 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_homepagecarousel_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='homepage/hero-carousel/', verbose_name='Slide Image')),
                ('badge_text', models.CharField(blank=True, max_length=60, verbose_name='Badge Text')),
                ('heading', models.CharField(max_length=160, verbose_name='Heading')),
                ('description', models.CharField(blank=True, max_length=260, verbose_name='Description')),
                ('button_text', models.CharField(blank=True, max_length=80, verbose_name='Button Text')),
                ('button_url', models.URLField(blank=True, max_length=500, verbose_name='Button URL')),
                ('image_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='right', max_length=20, verbose_name='Image Alignment')),
                ('text_alignment', models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=20, verbose_name='Text Alignment')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='Display Order')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('slide_duration', models.PositiveIntegerField(default=5000, verbose_name='Slide Duration (ms)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
            ],
            options={
                'verbose_name': 'Hero Banner Carousel',
                'verbose_name_plural': 'Hero Banner Carousels',
                'ordering': ['display_order', 'created_at', 'id'],
            },
        ),
    ]
