# Generated by Django 6.0.6 on 2026-06-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_bannercarousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarousel',
            name='badge_margin_bottom',
            field=models.PositiveIntegerField(blank=True, default=14, verbose_name='Badge Margin Bottom'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_margin_bottom',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Button Margin Bottom'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_margin_top',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Button Margin Top'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='content_padding_bottom',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Content Padding Bottom'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='content_padding_left',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Content Padding Left'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='content_padding_right',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Content Padding Right'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='content_padding_top',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Content Padding Top'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='description_margin_bottom',
            field=models.PositiveIntegerField(blank=True, default=24, verbose_name='Description Margin Bottom'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='desktop_content_width',
            field=models.PositiveIntegerField(blank=True, default=50, verbose_name='Desktop Content Width (%)'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='desktop_image_width',
            field=models.PositiveIntegerField(blank=True, default=50, verbose_name='Desktop Image Width (%)'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='heading_margin_bottom',
            field=models.PositiveIntegerField(blank=True, default=10, verbose_name='Heading Margin Bottom'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='image_margin_bottom',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Image Margin Bottom'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='image_margin_left',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Image Margin Left'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='image_margin_right',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Image Margin Right'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='image_margin_top',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Image Margin Top'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='image_max_height',
            field=models.PositiveIntegerField(blank=True, default=250, verbose_name='Image Max Height (px)'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='image_max_width',
            field=models.PositiveIntegerField(blank=True, default=100, verbose_name='Image Max Width (%)'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='mobile_content_padding',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Mobile Content Padding'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='mobile_image_width',
            field=models.PositiveIntegerField(blank=True, default=100, verbose_name='Mobile Image Width (%)'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='section_margin_bottom',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Section Margin Bottom'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='section_margin_top',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Section Margin Top'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='section_padding_bottom',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Section Padding Bottom'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='section_padding_left',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Section Padding Left'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='section_padding_right',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Section Padding Right'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='section_padding_top',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Section Padding Top'),
        ),
    ]
