# Generated by Django 6.0.6 on 2026-06-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_bannercarousel_badge_margin_bottom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bannercarousel',
            name='badge_margin_bottom',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='button_margin_bottom',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='button_margin_top',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='content_padding_bottom',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='content_padding_left',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='content_padding_right',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='content_padding_top',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='description_margin_bottom',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='desktop_content_width',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='desktop_image_width',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='heading_margin_bottom',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='image_alignment',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='image_margin_bottom',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='image_margin_left',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='image_margin_right',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='image_margin_top',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='image_max_height',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='image_max_width',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='mobile_content_padding',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='mobile_image_width',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='section_margin_bottom',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='section_margin_top',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='section_padding_bottom',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='section_padding_left',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='section_padding_right',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='section_padding_top',
        ),
        migrations.RemoveField(
            model_name='bannercarousel',
            name='text_alignment',
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='layout_template',
            field=models.CharField(choices=[('layout_1', 'Layout 1 = Text Left + Image Right'), ('layout_2', 'Layout 2 = Image Left + Text Right'), ('layout_3', 'Layout 3 = Center Content'), ('layout_4', 'Layout 4 = Full Background Banner'), ('layout_5', 'Layout 5 = Right Image with Overlay Text'), ('layout_6', 'Layout 6 = Left Image with Overlay Text')], default='layout_1', max_length=30, verbose_name='Banner Layout Template'),
        ),
    ]
