# Generated by Django 6.0.6 on 2026-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_remove_bannercarousel_badge_margin_bottom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarousel',
            name='left_badge_text',
            field=models.CharField(blank=True, max_length=60, verbose_name='Left Badge Text'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='left_button_text',
            field=models.CharField(blank=True, max_length=80, verbose_name='Left Button Text'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='left_button_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Left Button URL'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='left_description',
            field=models.CharField(blank=True, max_length=260, verbose_name='Left Description'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='left_heading',
            field=models.CharField(blank=True, max_length=160, verbose_name='Left Heading'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='right_badge_text',
            field=models.CharField(blank=True, max_length=60, verbose_name='Right Badge Text'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='right_button_text',
            field=models.CharField(blank=True, max_length=80, verbose_name='Right Button Text'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='right_button_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Right Button URL'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='right_description',
            field=models.CharField(blank=True, max_length=260, verbose_name='Right Description'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='right_heading',
            field=models.CharField(blank=True, max_length=160, verbose_name='Right Heading'),
        ),
        migrations.AlterField(
            model_name='bannercarousel',
            name='layout_template',
            field=models.CharField(choices=[('layout_1', 'Layout 1 = Text Left + Image Right'), ('layout_2', 'Layout 2 = Image Left + Text Right'), ('layout_3', 'Layout 3 = Center Content'), ('layout_4', 'Layout 4 = Full Background Banner'), ('layout_5', 'Layout 5 = Right Image with Overlay Text'), ('layout_6', 'Layout 6 = Left Image with Overlay Text'), ('layout_7', 'Layout 7 = Split Text + Center Image')], default='layout_1', max_length=30, verbose_name='Banner Layout Template'),
        ),
    ]
