# Generated by Django 6.0.6 on 2026-06-25 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0009_bannercarousel_left_badge_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarousel',
            name='show_badge',
            field=models.BooleanField(default=True, verbose_name='Show Badge'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_button',
            field=models.BooleanField(default=True, verbose_name='Show Button'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_description',
            field=models.BooleanField(default=True, verbose_name='Show Description'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_heading',
            field=models.BooleanField(default=True, verbose_name='Show Heading'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_image',
            field=models.BooleanField(default=True, verbose_name='Show Image'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_left_content',
            field=models.BooleanField(default=True, verbose_name='Show Left Content'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_right_content',
            field=models.BooleanField(default=True, verbose_name='Show Right Content'),
        ),
    ]
