# Generated by Django 6.0.6 on 2026-06-25 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0010_bannercarousel_show_badge_bannercarousel_show_button_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarousel',
            name='animation_delay',
            field=models.PositiveIntegerField(default=0, verbose_name='Animation Delay (ms)'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='animation_duration',
            field=models.PositiveIntegerField(default=800, verbose_name='Animation Duration (ms)'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_color',
            field=models.CharField(default='#f3f4f6', max_length=20, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_gradient_color_1',
            field=models.CharField(default='#f8fafc', max_length=20, verbose_name='Gradient Color 1'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_gradient_color_2',
            field=models.CharField(default='#e2e8f0', max_length=20, verbose_name='Gradient Color 2'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_gradient_direction',
            field=models.CharField(choices=[('to right', 'Left to Right'), ('to left', 'Right to Left'), ('to bottom', 'Top to Bottom'), ('to top', 'Bottom to Top'), ('45deg', 'Diagonal')], default='to right', max_length=20, verbose_name='Gradient Direction'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='homepage/hero-backgrounds/', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_overlay_color',
            field=models.CharField(default='#111827', max_length=20, verbose_name='Overlay Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_overlay_opacity',
            field=models.DecimalField(decimal_places=2, default=0.2, max_digits=3, verbose_name='Overlay Opacity'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_position',
            field=models.CharField(default='center center', max_length=30, verbose_name='Background Position'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_repeat',
            field=models.CharField(default='no-repeat', max_length=20, verbose_name='Background Repeat'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_size',
            field=models.CharField(default='cover', max_length=20, verbose_name='Background Size'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='background_type',
            field=models.CharField(choices=[('solid', 'Solid Color'), ('gradient', 'Gradient'), ('image', 'Image Background')], default='solid', max_length=20, verbose_name='Background Type'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='badge_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade-in', 'Fade In'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom-in', 'Zoom In'), ('zoom-out', 'Zoom Out'), ('bounce', 'Bounce'), ('pulse', 'Pulse')], default='none', max_length=20, verbose_name='Badge Animation'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='badge_font_size',
            field=models.CharField(default='0.8rem', max_length=20, verbose_name='Badge Font Size'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='badge_font_weight',
            field=models.CharField(default='700', max_length=20, verbose_name='Badge Font Weight'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='badge_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Badge Text Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade-in', 'Fade In'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom-in', 'Zoom In'), ('zoom-out', 'Zoom Out'), ('bounce', 'Bounce'), ('pulse', 'Pulse')], default='none', max_length=20, verbose_name='Button Animation'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_background_color',
            field=models.CharField(default='#ffb800', max_length=20, verbose_name='Button Background Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_border_color',
            field=models.CharField(default='#ffb800', max_length=20, verbose_name='Button Border Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_border_radius',
            field=models.PositiveIntegerField(default=8, verbose_name='Button Border Radius'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_font_size',
            field=models.CharField(default='0.95rem', max_length=20, verbose_name='Button Font Size'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_font_weight',
            field=models.CharField(default='600', max_length=20, verbose_name='Button Font Weight'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_height',
            field=models.CharField(default='auto', max_length=20, verbose_name='Button Height'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_hover_background_color',
            field=models.CharField(default='#e19c00', max_length=20, verbose_name='Hover Background Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_hover_border_color',
            field=models.CharField(default='#e19c00', max_length=20, verbose_name='Hover Border Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_hover_shadow',
            field=models.BooleanField(default=True, verbose_name='Hover Shadow'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_hover_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Hover Text Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_padding',
            field=models.CharField(default='0.75rem 1.25rem', max_length=40, verbose_name='Button Padding'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_text_color',
            field=models.CharField(default='#ffffff', max_length=20, verbose_name='Button Text Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_variant',
            field=models.CharField(choices=[('solid', 'Solid'), ('outline', 'Outline'), ('rounded', 'Rounded'), ('pill', 'Pill'), ('ghost', 'Ghost')], default='solid', max_length=20, verbose_name='Button Style'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_width',
            field=models.CharField(default='auto', max_length=20, verbose_name='Button Width'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='clicks_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Banner Clicks'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='description_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade-in', 'Fade In'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom-in', 'Zoom In'), ('zoom-out', 'Zoom Out'), ('bounce', 'Bounce'), ('pulse', 'Pulse')], default='none', max_length=20, verbose_name='Description Animation'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='description_font_size',
            field=models.CharField(default='1rem', max_length=20, verbose_name='Description Font Size'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='description_font_weight',
            field=models.CharField(default='400', max_length=20, verbose_name='Description Font Weight'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='description_text_color',
            field=models.CharField(default='#4b5563', max_length=20, verbose_name='Description Text Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='heading_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade-in', 'Fade In'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom-in', 'Zoom In'), ('zoom-out', 'Zoom Out'), ('bounce', 'Bounce'), ('pulse', 'Pulse')], default='none', max_length=20, verbose_name='Heading Animation'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='heading_font_size',
            field=models.CharField(default='clamp(2rem, 4vw, 3.5rem)', max_length=30, verbose_name='Heading Font Size'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='heading_font_weight',
            field=models.CharField(default='700', max_length=20, verbose_name='Heading Font Weight'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='heading_text_color',
            field=models.CharField(default='#111827', max_length=20, verbose_name='Heading Text Color'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='image_animation',
            field=models.CharField(choices=[('none', 'None'), ('fade-in', 'Fade In'), ('fade-up', 'Fade Up'), ('fade-down', 'Fade Down'), ('slide-left', 'Slide Left'), ('slide-right', 'Slide Right'), ('zoom-in', 'Zoom In'), ('zoom-out', 'Zoom Out'), ('bounce', 'Bounce'), ('pulse', 'Pulse')], default='none', max_length=20, verbose_name='Image Animation'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_on_desktop',
            field=models.BooleanField(default=True, verbose_name='Show on Desktop'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_on_mobile',
            field=models.BooleanField(default=True, verbose_name='Show on Mobile'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='show_on_tablet',
            field=models.BooleanField(default=True, verbose_name='Show on Tablet'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Banner Views'),
        ),
    ]
