# Generated by Django 6.0.6 on 2026-06-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0012_bannercarousel_enable_overlay'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='show_categories',
            field=models.BooleanField(default=True, verbose_name='Categories Enable'),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='show_top_brands',
            field=models.BooleanField(default=True, verbose_name='Top Brands Enable'),
        ),
    ]
