# Generated by Django 6.0.6 on 2026-06-30 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0013_homepagesettings_show_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bannercarousel',
            name='badge_font_family',
            field=models.CharField(default='Inter', max_length=100, verbose_name='Badge Font Family'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='button_font_family',
            field=models.CharField(default='Inter', max_length=100, verbose_name='Button Font Family'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='description_font_family',
            field=models.CharField(default='Inter', max_length=100, verbose_name='Description Font Family'),
        ),
        migrations.AddField(
            model_name='bannercarousel',
            name='heading_font_family',
            field=models.CharField(default='Inter', max_length=100, verbose_name='Heading Font Family'),
        ),
    ]
