# Generated by Django 6.0.6 on 2026-07-19 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def assign_default_collections(apps, schema_editor):
    Wishlist = apps.get_model('wishlist', 'Wishlist')
    WishlistCollection = apps.get_model('wishlist', 'WishlistCollection')
    for user_id in Wishlist.objects.values_list('user_id', flat=True).distinct().iterator():
        collection, _ = WishlistCollection.objects.get_or_create(user_id=user_id, name='Favorites')
        for item in Wishlist.objects.filter(user_id=user_id, collection__isnull=True).select_related('product').iterator():
            item.collection_id = collection.pk
            item.price_at_add = item.product.price
            item.save(update_fields=('collection', 'price_at_add'))


def unassign_default_collections(apps, schema_editor):
    apps.get_model('wishlist', 'Wishlist').objects.update(collection=None)


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_customerexperiencesettings_and_more'),
        ('wishlist', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishlistSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_collections_per_user', models.PositiveSmallIntegerField(default=10)),
                ('max_items_per_collection', models.PositiveSmallIntegerField(default=100)),
                ('allow_public_sharing', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Wishlist settings',
                'verbose_name_plural': 'Wishlist settings',
            },
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'ordering': ('-created_at', '-id')},
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='price_at_add',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='wishlist',
            name='saved_for_later',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='WishlistCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('share_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.AddField(
            model_name='wishlist',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlistcollection'),
        ),
        migrations.RunPython(assign_default_collections, unassign_default_collections),
        migrations.AlterField(
            model_name='wishlist',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlist.wishlistcollection'),
        ),
        migrations.AddConstraint(
            model_name='wishlist',
            constraint=models.UniqueConstraint(fields=('collection', 'product'), name='unique_product_per_wishlist_collection'),
        ),
        migrations.AddConstraint(
            model_name='wishlistcollection',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_wishlist_collection_name'),
        ),
    ]
