# Generated by Django 6.0.6 on 2026-07-01 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('author', models.CharField(default='OwnBasket', max_length=100)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='theme_previews/')),
                ('is_active', models.BooleanField(default=False)),
                ('is_custom', models.BooleanField(default=False)),
                ('header_layout', models.CharField(choices=[('header1', 'Header 1'), ('header2', 'Header 2'), ('header3', 'Header 3'), ('header4', 'Header 4'), ('header5', 'Header 5')], default='header1', max_length=50)),
                ('hero_layout', models.CharField(choices=[('hero1', 'Hero 1'), ('hero2', 'Hero 2'), ('hero3', 'Hero 3'), ('hero4', 'Hero 4'), ('hero5', 'Hero 5'), ('hero_slider', 'Hero Slider'), ('video_hero', 'Video Hero'), ('split_hero', 'Split Hero')], default='hero1', max_length=50)),
                ('category_layout', models.CharField(choices=[('layout1', 'Layout 1'), ('layout2', 'Layout 2'), ('layout3', 'Layout 3'), ('layout4', 'Layout 4')], default='layout1', max_length=50)),
                ('brand_layout', models.CharField(choices=[('layout1', 'Layout 1'), ('layout2', 'Layout 2'), ('layout3', 'Layout 3')], default='layout1', max_length=50)),
                ('product_card_layout', models.CharField(choices=[('card1', 'Card 1'), ('card2', 'Card 2'), ('card3', 'Card 3'), ('card4', 'Card 4'), ('card5', 'Card 5'), ('card6', 'Card 6'), ('amazon', 'Amazon Style'), ('minimal', 'Minimal'), ('luxury', 'Luxury'), ('glass', 'Glass')], default='card1', max_length=50)),
                ('product_detail_layout', models.CharField(choices=[('layout1', 'Layout 1'), ('layout2', 'Layout 2'), ('layout3', 'Layout 3'), ('layout4', 'Layout 4')], default='layout1', max_length=50)),
                ('cart_layout', models.CharField(choices=[('layout1', 'Layout 1'), ('layout2', 'Layout 2'), ('layout3', 'Layout 3')], default='layout1', max_length=50)),
                ('checkout_layout', models.CharField(choices=[('layout1', 'Layout 1'), ('layout2', 'Layout 2'), ('layout3', 'Layout 3')], default='layout1', max_length=50)),
                ('footer_layout', models.CharField(choices=[('footer1', 'Footer 1'), ('footer2', 'Footer 2'), ('footer3', 'Footer 3'), ('footer4', 'Footer 4'), ('footer5', 'Footer 5')], default='footer1', max_length=50)),
                ('theme_folder', models.CharField(help_text='Folder name inside themes directory', max_length=100, unique=True)),
                ('primary_color', models.CharField(default='#ffb800', help_text='Hex code of primary color (e.g. #ffb800)', max_length=7)),
                ('secondary_color', models.CharField(default='#232f3e', help_text='Hex code of secondary color', max_length=7)),
                ('accent_color', models.CharField(default='#ffb800', help_text='Hex code of accent color', max_length=7)),
                ('bg_color', models.CharField(default='#f4f6f9', help_text='Hex code of background color', max_length=7)),
                ('text_color', models.CharField(default='#1a1a1a', help_text='Hex code of text color', max_length=7)),
                ('border_color', models.CharField(default='#eaecf0', help_text='Hex code of border color', max_length=7)),
                ('button_color', models.CharField(default='#ffb800', help_text='Hex code of button color', max_length=7)),
                ('hover_color', models.CharField(default='#e0a200', help_text='Hex code of button hover color', max_length=7)),
                ('font_family', models.CharField(choices=[('Poppins', 'Poppins'), ('Inter', 'Inter'), ('Outfit', 'Outfit'), ('Montserrat', 'Montserrat'), ('Nunito', 'Nunito'), ('Lato', 'Lato'), ('Raleway', 'Raleway'), ('Roboto', 'Roboto'), ('Oswald', 'Oswald'), ('Playfair Display', 'Playfair Display'), ('Merriweather', 'Merriweather'), ('Bebas Neue', 'Bebas Neue'), ('Caveat', 'Caveat'), ('Pacifico', 'Pacifico'), ('Great Vibes', 'Great Vibes'), ('Dancing Script', 'Dancing Script')], default='Inter', max_length=50)),
                ('border_radius', models.CharField(choices=[('0px', '0px'), ('5px', '5px'), ('10px', '10px'), ('15px', '15px'), ('20px', '20px'), ('25px', '25px')], default='10px', max_length=10)),
                ('button_style', models.CharField(choices=[('rounded', 'Rounded'), ('square', 'Square'), ('pill', 'Pill'), ('outline', 'Outline'), ('gradient', 'Gradient'), ('glass', 'Glass')], default='rounded', max_length=20)),
                ('animation_style', models.CharField(choices=[('none', 'None'), ('fade', 'Fade'), ('zoom', 'Zoom'), ('slide', 'Slide'), ('scale', 'Scale'), ('flip', 'Flip')], default='none', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
