# Generated by Django 6.0.6 on 2026-07-02 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='template_mappings',
            field=models.JSONField(blank=True, default=dict, help_text='Mapping of OwnBasket page types to imported HTML template files.'),
        ),
        migrations.CreateModel(
            name='TemplateConversionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the template file within the theme folder.', max_length=500)),
                ('line_number', models.PositiveIntegerField(blank=True, null=True)),
                ('target_selector', models.TextField(help_text='CSS selector to identify the target element for modification.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPLIED', 'Applied'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('conversion_type', models.CharField(choices=[('VAR', 'Variable'), ('LOOP', 'For Loop'), ('IMAGE', 'Image'), ('URL', 'URL'), ('UNKNOWN', 'Unknown'), ('WRAP', 'Wrapper')], default='UNKNOWN', max_length=10)),
                ('original_html', models.TextField(help_text='The original HTML snippet.')),
                ('suggested_code', models.TextField(help_text='The suggested Django template code.')),
                ('confidence', models.FloatField(default=0.0, help_text='Confidence score of the suggestion (0.0 to 1.0).')),
                ('description', models.CharField(help_text='Explanation of the suggested change.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_logs', to='themes.theme')),
            ],
            options={
                'verbose_name': 'Template Conversion Suggestion',
                'verbose_name_plural': 'Template Conversion Suggestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThemeFileBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(help_text='Path to the template file within the theme folder.', max_length=500)),
                ('version', models.PositiveIntegerField()),
                ('backup_file_path', models.CharField(help_text='Path to the stored backup file.', max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('restored_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='themes.themefilebackup')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_backups', to='themes.theme')),
            ],
            options={
                'verbose_name': 'Theme File Backup',
                'verbose_name_plural': 'Theme File Backups',
                'ordering': ['-version'],
                'unique_together': {('theme', 'file_path', 'version')},
            },
        ),
    ]
