# Generated by Django 6.0.6 on 2026-07-06 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_theme_template_mappings_templateconversionlog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='border_style',
            field=models.CharField(default='solid', help_text='Specifies the global border style (e.g., solid, dashed).', max_length=50),
        ),
        migrations.AddField(
            model_name='theme',
            name='border_width',
            field=models.PositiveIntegerField(default=1, help_text='Defines the global border width for elements (in pixels).'),
        ),
        migrations.AddField(
            model_name='theme',
            name='button_shadow',
            field=models.CharField(default='0 1px 2px 0 rgba(0, 0, 0, 0.05)', help_text='Adds a subtle shadow to buttons.', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_shadow',
            field=models.CharField(default='0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -2px rgba(0, 0, 0, 0.1)', help_text='Sets the box-shadow for card elements.', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='container_width',
            field=models.PositiveIntegerField(default=1200, help_text='Controls the max-width of primary layout containers (in pixels).'),
        ),
        migrations.AddField(
            model_name='theme',
            name='footer_width',
            field=models.CharField(choices=[('container', 'Contained'), ('fluid', 'Full Width')], default='container', help_text='Determines if footer content is contained or spans the full width.', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='global_loader_toggle',
            field=models.BooleanField(default=True, help_text='Enable or disable the site-wide pre-loader animation.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='global_transition_speed',
            field=models.CharField(default='0.3s', help_text='Sets a consistent duration for CSS transitions (e.g., 0.3s).', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='hover_animation_style',
            field=models.CharField(default='scale', help_text='Defines a global hover effect (e.g., scale, lift, none).', max_length=50),
        ),
        migrations.AddField(
            model_name='theme',
            name='image_border_radius',
            field=models.PositiveIntegerField(default=8, help_text='Controls the corner rounding for images (in pixels).'),
        ),
        migrations.AddField(
            model_name='theme',
            name='input_border_radius',
            field=models.PositiveIntegerField(default=6, help_text='Sets the border radius for form inputs (in pixels).'),
        ),
        migrations.AddField(
            model_name='theme',
            name='navbar_height',
            field=models.PositiveIntegerField(default=80, help_text='Specifies the height of the main navigation bar (in pixels).'),
        ),
        migrations.AddField(
            model_name='theme',
            name='scroll_to_top_toggle',
            field=models.BooleanField(default=True, help_text="Show or hide a 'scroll to top' button on long pages."),
        ),
        migrations.AddField(
            model_name='theme',
            name='section_spacing',
            field=models.PositiveIntegerField(default=60, help_text='Defines default top/bottom padding for major sections (in pixels).'),
        ),
    ]
