# Generated by Django 6.0.6 on 2026-07-06 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_theme_border_style_theme_border_width_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='primary_color',
            new_name='brand_primary_color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='secondary_color',
            new_name='brand_secondary_color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='accent_color',
            new_name='brand_accent_color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='bg_color',
            new_name='bg_body_color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='text_color',
            new_name='text_primary_color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='border_color',
            new_name='border_global_color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='button_color',
            new_name='btn_primary_bg_color',
        ),
        migrations.RenameField(
            model_name='theme',
            old_name='hover_color',
            new_name='btn_primary_hover_bg_color',
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_card_color',
            field=models.CharField(default='#ffffff', help_text='Background color for cards and panels.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_footer_color',
            field=models.CharField(default='#232f3e', help_text='Background color of the site footer.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_header_color',
            field=models.CharField(default='#ffffff', help_text='Background color of the site header.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='bg_section_color',
            field=models.CharField(default='#ffffff', help_text='Background color for content sections.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='border_card_color',
            field=models.CharField(default='#eaecf0', help_text='Specific border color for card elements.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='border_input_color',
            field=models.CharField(default='#ced4da', help_text='Border color for form input fields.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_secondary_bg_color',
            field=models.CharField(default='#343a40', help_text='Background color for secondary buttons.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_secondary_hover_bg_color',
            field=models.CharField(default='#232f3e', help_text='Background color for secondary buttons on hover.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='product_discount_badge_bg_color',
            field=models.CharField(default='#d92d20', help_text='Background color for the discount badge.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='product_discount_badge_text_color',
            field=models.CharField(default='#ffffff', help_text='Text color for the discount badge.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='product_price_color',
            field=models.CharField(default='#d92d20', help_text='Color for the main product price.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='product_sale_price_color',
            field=models.CharField(default='#d92d20', help_text='Color for the sale price when a product is discounted.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='status_danger_color',
            field=models.CharField(default='#d92d20', help_text='Color for error messages and danger actions.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='status_info_color',
            field=models.CharField(default='#007bff', help_text='Color for informational messages.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='status_success_color',
            field=models.CharField(default='#039855', help_text='Color for success messages and indicators.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='status_warning_color',
            field=models.CharField(default='#f79009', help_text='Color for warnings and alerts.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_heading_color',
            field=models.CharField(default='#212529', help_text='Color for all heading elements (h1, h2, etc.).', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_link_color',
            field=models.CharField(default='#ffb800', help_text='Default color for hyperlinks.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_link_hover_color',
            field=models.CharField(default='#e0a200', help_text='Color for hyperlinks on hover.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='text_secondary_color',
            field=models.CharField(default='#6c757d', help_text='Secondary text color for meta information and subtitles.', max_length=7),
        ),
    ]
