# Generated by Django 6.0.6 on 2026-07-06 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0004_add_color_palette'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='alert_padding',
            field=models.CharField(default='1rem', help_text='Padding for alerts.', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='alert_radius',
            field=models.PositiveIntegerField(default=8, help_text='Alert box border radius in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='alert_shadow',
            field=models.CharField(default='0 4px 12px rgba(0, 0, 0, 0.08)', help_text='Shadow for alert boxes.', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='badge_font_size',
            field=models.PositiveIntegerField(default=11, help_text='Font size for badges.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='badge_padding',
            field=models.CharField(default='6px 12px', help_text='Padding for badges.', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='badge_radius',
            field=models.PositiveIntegerField(default=999, help_text='Badge border radius in pixels (999 for pill shape).'),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_border_radius',
            field=models.PositiveIntegerField(default=8, help_text='Button border radius in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_border_style',
            field=models.CharField(default='solid', help_text='Button border style (solid, dashed, etc.).', max_length=10),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_border_width',
            field=models.PositiveIntegerField(default=1, help_text='Button border width in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_font_size',
            field=models.PositiveIntegerField(default=16, help_text='Button font size in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_font_weight',
            field=models.PositiveIntegerField(default=700, help_text='Button font weight (e.g., 400, 700).'),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_hover_animation',
            field=models.CharField(default='translateY', help_text='Animation on hover (e.g., translateY, scale).', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_hover_scale',
            field=models.FloatField(default=1.05, help_text='Scale factor on hover (e.g., 1.05).'),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_hover_shadow',
            field=models.CharField(default='0 8px 24px rgba(0, 0, 0, 0.1)', help_text='Box shadow on hover.', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='btn_padding',
            field=models.CharField(default='12px 20px', help_text="Button padding (e.g., '12px 20px').", max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_border_radius',
            field=models.PositiveIntegerField(default=12, help_text='Card border radius in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_border_width',
            field=models.PositiveIntegerField(default=1, help_text='Card border width in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_box_shadow',
            field=models.CharField(default='0 8px 24px rgba(0, 0, 0, 0.06)', help_text='Card box shadow.', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_hover_lift_effect',
            field=models.BooleanField(default=True, help_text='Enable/disable card lift effect on hover.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_hover_shadow',
            field=models.CharField(default='0 14px 30px rgba(0, 0, 0, 0.08)', help_text='Card box shadow on hover.', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_image_radius',
            field=models.PositiveIntegerField(default=0, help_text='Radius for top images in cards.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='form_input_border_radius',
            field=models.PositiveIntegerField(default=8, help_text='Input field border radius in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='form_input_border_width',
            field=models.PositiveIntegerField(default=1, help_text='Input field border width in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='form_input_focus_color',
            field=models.CharField(default='#ffb800', help_text='Border color of focused input.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='form_input_height',
            field=models.PositiveIntegerField(default=46, help_text='Height of form input fields in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='form_label_style',
            field=models.CharField(default='normal', help_text='Style of form labels (e.g., normal, bold).', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='form_placeholder_color',
            field=models.CharField(default='#6c757d', help_text='Color of placeholder text.', max_length=7),
        ),
        migrations.AddField(
            model_name='theme',
            name='modal_radius',
            field=models.PositiveIntegerField(default=16, help_text='Modal dialog border radius in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='modal_shadow',
            field=models.CharField(default='0 14px 40px rgba(0, 0, 0, 0.15)', help_text='Shadow for modal dialogs.', max_length=100),
        ),
        migrations.AddField(
            model_name='theme',
            name='modal_width',
            field=models.PositiveIntegerField(default=500, help_text='Default width of modal dialogs in pixels.'),
        ),
        migrations.AddField(
            model_name='theme',
            name='table_border_style',
            field=models.CharField(default='horizontal', help_text='Table border style (e.g., horizontal, all).', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='table_header_style',
            field=models.CharField(default='bold', help_text='Style of table headers (e.g., bold, uppercase).', max_length=20),
        ),
        migrations.AddField(
            model_name='theme',
            name='table_row_hover',
            field=models.BooleanField(default=True, help_text='Enable/disable row hover effect.'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='bg_body_color',
            field=models.CharField(default='#f4f6f9', help_text='Main background color of the website body.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='border_global_color',
            field=models.CharField(default='#eaecf0', help_text='Global border color for elements like cards and tables.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='brand_accent_color',
            field=models.CharField(default='#ffb800', help_text='Accent color for special highlights and call-to-actions.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='brand_primary_color',
            field=models.CharField(default='#ffb800', help_text='Primary brand color for major UI elements.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='brand_secondary_color',
            field=models.CharField(default='#232f3e', help_text='Secondary brand color used for accents and backgrounds.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_primary_bg_color',
            field=models.CharField(default='#ffb800', help_text='Background color for primary buttons.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='btn_primary_hover_bg_color',
            field=models.CharField(default='#e0a200', help_text='Background color for primary buttons on hover.', max_length=7),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text_primary_color',
            field=models.CharField(default='#1a1a1a', help_text='Primary text color for body content.', max_length=7),
        ),
    ]
