# Generated by Django 6.0.6 on 2026-07-16 01:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('orders', 'Orders'), ('sales', 'Sales'), ('products', 'Products'), ('categories', 'Categories'), ('brands', 'Brands'), ('customers', 'Customers'), ('sellers', 'Sellers'), ('refunds', 'Refunds'), ('coupons', 'Coupons'), ('taxes', 'Taxes')], max_length=40)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=12)),
                ('recipient', models.EmailField(max_length=254)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel')], default='csv', max_length=8)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_sent', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scheduled_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('next_run', 'id'),
                'permissions': (('manage_scheduled_reports', 'Can manage scheduled reports'),),
            },
        ),
    ]
