# Generated by Django 6.0.6 on 2026-07-19 05:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('orders', '0007_paymenttransaction_refund_alter_order_options_and_more'),
        ('products', '0016_customerexperiencesettings_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketplaceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('mode', models.CharField(choices=[('single', 'Single vendor'), ('multi', 'Multi vendor')], default='multi', max_length=12)),
                ('seller_registration_enabled', models.BooleanField(default=True)),
                ('global_commission_rate', models.DecimalField(decimal_places=2, default=Decimal('10.00'), help_text='Default structure for future commission evaluation. Checkout behavior is unchanged.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('low_stock_notification_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Marketplace settings',
                'verbose_name_plural': 'Marketplace settings',
            },
        ),
        migrations.AddField(
            model_name='sellernotification',
            name='email_status',
            field=models.CharField(choices=[('not_requested', 'Not requested'), ('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='not_requested', max_length=16),
        ),
        migrations.AddField(
            model_name='sellernotification',
            name='event_type',
            field=models.CharField(choices=[('seller_approved', 'Seller approved'), ('seller_rejected', 'Seller rejected'), ('new_order', 'New order'), ('low_stock', 'Low stock'), ('review_received', 'Review received'), ('general', 'General')], db_index=True, default='general', max_length=24),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='identity_reference',
            field=models.CharField(blank=True, help_text='Masked or administrative identity reference; do not store raw credentials.', max_length=100),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='tax_registration_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.CreateModel(
            name='SellerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reserved_stock', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_inventory', to='products.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_records', to='marketplace.sellerprofile')),
            ],
            options={
                'ordering': ('product__name', 'id'),
                'permissions': (('adjust_seller_inventory', 'Can adjust seller inventory'),),
            },
        ),
        migrations.CreateModel(
            name='SellerOrderFulfillment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('packing', 'Packing'), ('ready_to_ship', 'Ready to ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], db_index=True, default='received', max_length=20)),
                ('seller_note', models.TextField(blank=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_fulfillments', to='orders.order')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fulfillments', to='marketplace.sellerprofile')),
            ],
            options={
                'ordering': ('-order__created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='SellerOrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('packing', 'Packing'), ('ready_to_ship', 'Ready to ship'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fulfillment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='marketplace.sellerorderfulfillment')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Reserved for future rule conditions.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='products.category')),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='marketplace.sellerprofile')),
            ],
            options={
                'ordering': ('priority', 'id'),
                'indexes': [models.Index(fields=['is_active', 'priority'], name='commission_active_priority_idx')],
            },
        ),
        migrations.CreateModel(
            name='InventoryHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_change', models.IntegerField(default=0)),
                ('reserved_change', models.IntegerField(default=0)),
                ('stock_after', models.PositiveIntegerField()),
                ('reserved_after', models.PositiveIntegerField()),
                ('reason', models.CharField(choices=[('manual', 'Manual adjustment'), ('order_reserved', 'Order reserved'), ('order_released', 'Order released'), ('order_fulfilled', 'Order fulfilled'), ('import', 'Import'), ('correction', 'Correction')], default='manual', max_length=24)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='marketplace.sellerinventory')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'indexes': [models.Index(fields=['inventory', 'created_at'], name='inventory_history_time_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='sellerorderfulfillment',
            index=models.Index(fields=['seller', 'status'], name='seller_fulfillment_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='sellerorderfulfillment',
            constraint=models.UniqueConstraint(fields=('seller', 'order'), name='unique_seller_order_fulfillment'),
        ),
    ]
