# Generated by Django 4.2.13 on 2024-07-29 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HomepageSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Internal name for this section in the admin.",
                        max_length=100,
                    ),
                ),
                (
                    "section_type",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("product_carousel", "Product Carousel"),
                            ("featured_categories", "Featured Categories"),
                            ("featured_brands", "Featured Brands"),
                            ("banner", "Banner Ad"),
                        ],
                        editable=False,
                        max_length=50,
                    ),
                ),
                (
                    "display_order",
                    models.PositiveIntegerField(db_index=True, default=0),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Homepage Section",
                "verbose_name_plural": "Homepage Sections",
                "ordering": ("display_order",),
            },
        ),
        migrations.CreateModel(
            name="HeroSection",
            fields=[
                (
                    "homepagesection_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="site_sections.homepagesection",
                    ),
                ),
                ("heading", models.CharField(blank=True, max_length=150)),
                ("subheading", models.CharField(blank=True, max_length=255)),
                (
                    "background_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="site_sections/hero/"
                    ),
                ),
                (
                    "background_color",
                    models.CharField(blank=True, default="#f4f6f9", max_length=20),
                ),
                ("button_text", models.CharField(blank=True, max_length=50)),
                ("button_url", models.CharField(blank=True, max_length=255)),
            ],
            options={
                "verbose_name": "Hero Section",
                "verbose_name_plural": "Hero Sections",
            },
            bases=("site_sections.homepagesection",),
        ),
    ]
