# Generated by Django 6.0.6 on 2026-07-17 01:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_hash', models.CharField(max_length=64)),
                ('platform', models.CharField(choices=[('web', 'Web/PWA'), ('android', 'Android (future)'), ('ios', 'iOS (future)')], default='web', max_length=12)),
                ('provider', models.CharField(choices=[('none', 'Not connected'), ('web_push', 'Web Push (future)'), ('fcm', 'Firebase Cloud Messaging (future)')], default='none', max_length=12)),
                ('notifications_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_seen_at', '-id'),
                'indexes': [models.Index(fields=['user', 'last_seen_at'], name='push_device_user_seen_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'device_id_hash'), name='unique_user_push_device')],
            },
        ),
    ]
