# Generated by Django 6.0.6 on 2026-07-18 05:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_v2', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pushdevice',
            name='app_version',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='failure_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='locale',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='provider_token_encrypted',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='provider_token_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pushdevice',
            name='token_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pushdevice',
            name='provider',
            field=models.CharField(choices=[('none', 'Not connected'), ('web_push', 'Web Push'), ('fcm', 'Firebase Cloud Messaging'), ('apns', 'Apple Push Notification service')], default='none', max_length=12),
        ),
        migrations.CreateModel(
            name='MobileSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_hash', models.CharField(max_length=64)),
                ('device_name', models.CharField(blank=True, max_length=120)),
                ('platform', models.CharField(default='unknown', max_length=12)),
                ('access_token_hash', models.CharField(max_length=64, unique=True)),
                ('refresh_token_hash', models.CharField(max_length=64, unique=True)),
                ('access_expires_at', models.DateTimeField(db_index=True)),
                ('refresh_expires_at', models.DateTimeField(db_index=True)),
                ('absolute_expires_at', models.DateTimeField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('revoked_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('revoke_reason', models.CharField(blank=True, max_length=40)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-last_used_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PushDelivery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_key', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=80)),
                ('body', models.CharField(max_length=240)),
                ('target_path', models.CharField(default='/home/', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('delivered', 'Delivered'), ('retry', 'Retry scheduled'), ('failed', 'Permanently failed'), ('cancelled', 'Cancelled')], db_index=True, default='queued', max_length=12)),
                ('attempt_count', models.PositiveSmallIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('provider_message_id', models.CharField(blank=True, max_length=160)),
                ('last_error_code', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='api_v2.pushdevice')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='SyncOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id_hash', models.CharField(max_length=64)),
                ('client_action_id', models.CharField(max_length=64)),
                ('operation', models.CharField(max_length=32)),
                ('payload_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('conflict', 'Conflict'), ('failed', 'Failed')], max_length=12)),
                ('result', models.JSONField(default=dict)),
                ('attempt_count', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sync_operations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveBigIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mobile_sync_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UsedRefreshToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True)),
                ('rotated_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_refresh_tokens', to='api_v2.mobilesession')),
            ],
            options={
                'ordering': ('-rotated_at',),
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_hash', models.CharField(max_length=64)),
                ('method', models.CharField(max_length=8)),
                ('path', models.CharField(max_length=255)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='processing', max_length=12)),
                ('response_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('response_body', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_idempotency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['expires_at', 'status'], name='idempotency_expiry_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'key_hash'), name='unique_user_idempotency_key')],
            },
        ),
        migrations.AddIndex(
            model_name='mobilesession',
            index=models.Index(fields=['user', 'device_id_hash', 'revoked_at'], name='mobile_session_device_idx'),
        ),
        migrations.AddIndex(
            model_name='pushdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='push_retry_queue_idx'),
        ),
        migrations.AddConstraint(
            model_name='pushdelivery',
            constraint=models.UniqueConstraint(fields=('device', 'event_key'), name='unique_push_event_per_device'),
        ),
        migrations.AddIndex(
            model_name='syncoperation',
            index=models.Index(fields=['user', 'updated_at'], name='sync_operation_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='syncoperation',
            constraint=models.UniqueConstraint(fields=('user', 'device_id_hash', 'client_action_id'), name='unique_mobile_sync_action'),
        ),
    ]
