# Generated by Django 6.0.6 on 2026-07-15 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_existing_user_carts(apps, schema_editor):
    Cart = apps.get_model('cart', 'Cart')
    app_label, model_name = settings.AUTH_USER_MODEL.split('.')
    User = apps.get_model(app_label, model_name)
    user_ids = set(User.objects.filter(pk__in=Cart.objects.values_list('pk', flat=True)).values_list('pk', flat=True))
    for user_id in user_ids:
        Cart.objects.filter(pk=user_id, user__isnull=True).update(user_id=user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_color_cartitem_size'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='last_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='reminder_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shopping_cart', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RunPython(link_existing_user_carts, migrations.RunPython.noop),
    ]
