# Generated by Django 6.0.6 on 2026-07-09 04:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_brandherobanner_banner_subtitle_and_more'),
        ('site_sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCarouselSection',
            fields=[
                ('homepagesection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='site_sections.homepagesection')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('source_type', models.CharField(choices=[('manual', 'Manually Selected Products'), ('featured', 'All Featured Products'), ('flash_sale', 'All Flash Sale Products'), ('latest', 'Latest Products'), ('best_selling', 'Best Selling Products'), ('trending', 'Trending Products (Most Views)'), ('category', 'Products from a Category'), ('brand', 'Products from a Brand')], default='manual', help_text='How to source products for this carousel.', max_length=20)),
                ('products_limit', models.PositiveIntegerField(default=8, help_text='Maximum number of products to display.')),
                ('button_text', models.CharField(blank=True, max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('background_color', models.CharField(blank=True, max_length=20)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='site_sections/carousels/')),
                ('layout_style', models.CharField(choices=[('slider', 'Slider'), ('grid', 'Grid')], default='slider', max_length=20)),
                ('brand', models.ForeignKey(blank=True, help_text="Required if source type is 'Brand'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand')),
                ('category', models.ForeignKey(blank=True, help_text="Required if source type is 'Category'.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('manual_products', models.ManyToManyField(blank=True, help_text="Required if source type is 'Manual'.", related_name='product_carousels', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Carousel Section',
                'verbose_name_plural': 'Product Carousel Sections',
            },
            bases=('site_sections.homepagesection',),
        ),
    ]
