# Generated by Django 6.0.6 on 2026-07-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_brandherobanner_banner_subtitle_and_more'),
        ('site_sections', '0002_productcarouselsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcarouselsection',
            name='autoplay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcarouselsection',
            name='autoplay_speed',
            field=models.PositiveIntegerField(default=4500, help_text='Milliseconds (2000–15000).'),
        ),
        migrations.AddField(
            model_name='productcarouselsection',
            name='loop',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcarouselsection',
            name='show_navigation',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcarouselsection',
            name='show_on_desktop',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcarouselsection',
            name='show_on_mobile',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productcarouselsection',
            name='show_pagination',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcarouselsection',
            name='show_view_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productcarouselsection',
            name='view_all_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='productcarouselsection',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.brand'),
        ),
        migrations.AlterField(
            model_name='productcarouselsection',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category'),
        ),
        migrations.AlterField(
            model_name='productcarouselsection',
            name='manual_products',
            field=models.ManyToManyField(blank=True, related_name='product_carousels', to='products.product'),
        ),
        migrations.AlterField(
            model_name='productcarouselsection',
            name='products_limit',
            field=models.PositiveIntegerField(default=8, help_text='Maximum products to display (1–48).'),
        ),
        migrations.AlterField(
            model_name='productcarouselsection',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manually Selected Products'), ('featured', 'Featured Products'), ('latest', 'Latest Products'), ('flash_sale', 'Flash Sale'), ('deal_of_the_day', 'Deal of the Day'), ('recommended', 'Recommended Products'), ('category', 'Products from a Category'), ('brand', 'Products from a Brand'), ('best_selling', 'Best Selling (legacy)'), ('trending', 'Trending (legacy)')], default='manual', max_length=20),
        ),
    ]
