# Generated by Django 6.0.6 on 2026-07-12 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_sections', '0003_productcarouselsection_autoplay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcarouselsection',
            name='view_all_text',
            field=models.CharField(blank=True, default='View all', max_length=40),
        ),
    ]
