# Generated by Django 6.0.6 on 2026-06-30 05:24

import django.core.validators
import fonts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Font Name')),
                ('css_name', models.CharField(max_length=180, verbose_name='CSS Font Family Name')),
                ('font_file', models.FileField(blank=True, help_text='Upload .ttf, .otf, .woff, or .woff2 files. WOFF2 is recommended for best performance.', null=True, upload_to=fonts.models.managed_font_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['ttf', 'otf', 'woff', 'woff2'])], verbose_name='Font File')),
                ('category', models.CharField(choices=[('script', 'Script'), ('sans-serif', 'Sans Serif'), ('serif', 'Serif'), ('handwriting', 'Handwriting'), ('display', 'Display'), ('monospace', 'Monospace')], default='sans-serif', max_length=20, verbose_name='Font Category')),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to=fonts.models.managed_font_preview_upload_to, verbose_name='Preview Image')),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('usage_count', models.PositiveIntegerField(default=0, editable=False, verbose_name='Usage Count')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last Used At')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Font',
                'verbose_name_plural': 'Fonts',
                'ordering': ['sort_order', 'name', 'id'],
            },
        ),
    ]
