# Generated by Django 6.0.6 on 2026-06-30 05:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0002_seed_default_fonts'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedFontPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Pack Name')),
                ('slug', models.SlugField(max_length=180, unique=True, verbose_name='Pack Slug')),
                ('group', models.CharField(choices=[('default', 'Default'), ('business', 'Business'), ('design', 'Design'), ('style', 'Style'), ('special', 'Special')], default='default', max_length=20, verbose_name='Pack Group')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Font Pack',
                'verbose_name_plural': 'Font Packs',
                'ordering': ['group', 'sort_order', 'name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ManagedFontPackFont',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Sort Order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('font', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pack_links', to='fonts.managedfont')),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='font_links', to='fonts.managedfontpack')),
            ],
            options={
                'verbose_name': 'Font Pack Item',
                'verbose_name_plural': 'Font Pack Items',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('pack', 'font')},
            },
        ),
        migrations.AddField(
            model_name='managedfont',
            name='packs',
            field=models.ManyToManyField(blank=True, related_name='fonts', through='fonts.ManagedFontPackFont', to='fonts.managedfontpack', verbose_name='Font Packs'),
        ),
    ]
