# Generated by Django 6.0.6 on 2026-06-30 06:06

from django.db import migrations, models


def seed_typography_catalog(apps, schema_editor):
    from fonts.services import bootstrap_typography_catalog

    bootstrap_typography_catalog()


class Migration(migrations.Migration):

    dependencies = [
        ('fonts', '0004_seed_default_font_packs'),
    ]

    operations = [
        migrations.AddField(
            model_name='managedfont',
            name='google_family',
            field=models.CharField(blank=True, help_text='Optional Google Fonts family name. Leave blank to use CSS Font Family Name.', max_length=180, verbose_name='Google Font Family Name'),
        ),
        migrations.AddField(
            model_name='managedfont',
            name='source',
            field=models.CharField(choices=[('upload', 'Uploaded Font'), ('google', 'Google Font')], default='upload', max_length=20, verbose_name='Font Source'),
        ),
        migrations.AddField(
            model_name='managedfont',
            name='style_label',
            field=models.CharField(blank=True, help_text='Short descriptor shown below the font name in the picker preview.', max_length=120, verbose_name='Preview Style Label'),
        ),
        migrations.RunPython(seed_typography_catalog, migrations.RunPython.noop),
    ]
