# Generated by Django 6.0.6 on 2026-07-15 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('orders', '0005_order_coupon_code_order_discount_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='marketplace_commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='marketplace.sellerprofile'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_earning',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_name',
            field=models.CharField(blank=True, max_length=160),
        ),
    ]
