# Generated by Django 6.0.6 on 2026-06-23 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_old_price_product_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productspecification',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
    ]
