# Generated by Django 6.0.6 on 2026-06-23 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_productspecification_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='rating',
        ),
        migrations.AddField(
            model_name='product',
            name='delivery_text',
            field=models.CharField(blank=True, default='FREE delivery Saturday, 28 June.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=4.5, max_digits=2),
        ),
        migrations.AddField(
            model_name='product',
            name='reviews_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
