# Generated by Django 6.0.6 on 2026-06-28 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandHeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_title', models.CharField(max_length=150)),
                ('banner_subtitle', models.CharField(blank=True, max_length=255)),
                ('button_text', models.CharField(blank=True, default='Shop Now', max_length=50)),
                ('button_url', models.CharField(blank=True, max_length=255)),
                ('cover_image', models.ImageField(upload_to='brands/hero_banners/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_banners', to='products.brand')),
            ],
            options={
                'verbose_name': 'Brand Hero Banner',
                'verbose_name_plural': 'Brand Hero Banners',
                'ordering': ('display_order', 'id'),
            },
        ),
    ]
