# Generated by Django 6.0.6 on 2026-06-28 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_brandherobanner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandherobanner',
            name='banner_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='brandherobanner',
            name='banner_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='brandherobanner',
            name='button_text',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='brandherobanner',
            name='button_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
