# Generated by Django 6.0.6 on 2026-07-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_brandherobanner_banner_subtitle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductListingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products_per_page', models.PositiveSmallIntegerField(default=24)),
                ('default_sort', models.CharField(default='default', max_length=20)),
                ('default_view', models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', max_length=10)),
                ('enable_filters', models.BooleanField(default=True)),
                ('enable_view_toggle', models.BooleanField(default=True)),
                ('enable_sidebar', models.BooleanField(default=True)),
                ('enable_sticky_filters', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Product listing settings',
                'verbose_name_plural': 'Product listing settings',
            },
        ),
    ]
