# Generated by Django 6.0.6 on 2026-07-15 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
        ('products', '0014_productreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Leave empty for products owned directly by OwnBasket.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='marketplace.sellerprofile'),
        ),
    ]
