# Generated by Django 6.0.6 on 2026-07-19 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_seller'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerExperienceSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recently_viewed_limit', models.PositiveSmallIntegerField(default=12)),
                ('recently_viewed_retention_days', models.PositiveSmallIntegerField(default=90)),
                ('related_products_limit', models.PositiveSmallIntegerField(default=8)),
                ('similar_price_min_percent', models.PositiveSmallIntegerField(default=60)),
                ('similar_price_max_percent', models.PositiveSmallIntegerField(default=140)),
                ('bought_together_limit', models.PositiveSmallIntegerField(default=4)),
                ('allow_bought_together_fallback', models.BooleanField(default=True)),
                ('compare_limit', models.PositiveSmallIntegerField(default=4)),
                ('reviews_per_page', models.PositiveSmallIntegerField(default=10)),
                ('max_review_images', models.PositiveSmallIntegerField(default=3)),
                ('review_minimum_characters', models.PositiveSmallIntegerField(default=20)),
            ],
            options={
                'verbose_name': 'Customer experience settings',
                'verbose_name_plural': 'Customer experience settings',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='availability_message',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='product',
            name='availability_mode',
            field=models.CharField(choices=[('auto', 'Automatic from stock'), ('in_stock', 'In stock'), ('out_of_stock', 'Out of stock'), ('pre_order', 'Pre order')], default='auto', max_length=16),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_restock_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productreview',
            name='helpful_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productreview',
            name='is_spam',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='productreview',
            name='verified_purchase',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.CreateModel(
            name='ProductBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=40, unique=True)),
                ('color', models.CharField(default='#ffb800', max_length=20)),
                ('text_color', models.CharField(default='#131921', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('products', models.ManyToManyField(blank=True, related_name='custom_badges', to='products.product')),
            ],
            options={
                'ordering': ('priority', 'label'),
            },
        ),
        migrations.CreateModel(
            name='ProductReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/')),
                ('alt_text', models.CharField(blank=True, max_length=160)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productreview')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ReviewHelpfulVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helpful_votes', to='products.productreview')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_helpful_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'user'), name='unique_helpful_vote_per_user')],
            },
        ),
    ]
